{% set name = "flair" %}
{% set version = "0.6" %}
 
package:
  name: python-flair
  version: {{ version }}

source:
  url: https://github.com/flairNLP/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cf445bbbb485faa3e49a3e46b6580aa84b18640288d9ce8e9dacc7a9266e27c6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux or py<36]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - python-dateutil
    - pytorch
    - gensim >=3.4.0
    - pytest >=5.3.2
    - tqdm >=4.26.0
    - segtok
    - matplotlib-base >=2.2.3
    - mpld3
    - scikit-learn >=0.21.3
    - sqlitedict >=1.6.0
    - deprecated >=1.2.4
    - hyperopt >=0.1.1
    - transformers
    - bpemb
    - tabulate
    - langdetect
    - sentencepiece
    - dataclasses  # [py36]

test:
  imports:
    - flair
    - flair.data
    - flair.models

about:
  home: https://github.com/flairNLP/flair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A very simple framework for state-of-the-art NLP.
  doc_url: https://pypi.org/project/flair/
  dev_url: https://github.com/flairNLP/flair

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
