{% set name = "flair" %}
{% set version = "0.7" %}


package:
  name: python-flair
  version: {{ version }}

source:
  url: https://github.com/flairNLP/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5d6cba2deed209c59534f2a00cbbde4de151c9d867f093b9f96b191d88454245

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bpemb >=0.3.2
    - deprecated >=1.2.4
    - ftfy
    - gdown
    - gensim <=3.8.3,>=3.4.0
    - hyperopt >=0.1.1
    - janome
    - konoha <5.0.0,>=4.0.0
    - langdetect
    - lxml
    - matplotlib-base >=2.2.3
    - mpld3 ==0.3
    - python >=3.6
    - python-dateutil >=2.6.1
    - regex
    - scikit-learn >=0.21.3
    - segtok >=1.5.7
    - sentencepiece <=0.1.91
    - sqlitedict >=1.6.0
    - tabulate
    - pytorch >=1.1.0
    - tqdm >=4.26.0
    - transformers <=3.5.1,>=3.5.0

test:
  imports:
    - flair
    - flair.data
    - flair.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flairNLP/flair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A very simple framework for state-of-the-art NLP.
  doc_url: https://pypi.org/project/flair/
  dev_url: https://github.com/flairNLP/flair

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
