{% set name = "flair" %}
{% set version = "0.8" %}


package:
  name: python-flair
  version: {{ version }}

source:
  url: https://github.com/flairNLP/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 00bb0561e8095eb03d7d4d49bc9658cdc065e3b383782e44914b3f421b6ac3bd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bpemb >=0.3.2
    - deprecated >=1.2.4
    - ftfy
    - gdown >=3.12.2
    - gensim <=3.8.3,>=3.4.0
    - huggingface_hub
    - hyperopt >=0.1.1
    - janome
    - konoha <5.0.0,>=4.0.0
    - langdetect
    - lxml
    - matplotlib-base >=2.2.3
    - mpld3 >=0.3
    - numpy
    - python >=3.6
    - python-dateutil >=2.6.1
    - regex
    - scikit-learn >=0.21.3
    - segtok >=1.5.7
    - sentencepiece >=0.1.95
    - sqlitedict >=1.6.0
    - tabulate
    - pytorch >=1.5.0
    - tqdm >=4.26.0
    - transformers >=4.0.0

test:
  imports:
    - flair
    - flair.data
    - flair.models
  commands:
    - pytest
  requires:
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/flairNLP/flair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A very simple framework for state-of-the-art NLP.
  doc_url: https://pypi.org/project/flair/
  dev_url: https://github.com/flairNLP/flair

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - BastianZim
