{% set name = "flair" %}
{% set version = "0.15.0" %}


package:
  name: python-flair
  version: {{ version }}

source:
  url: https://github.com/flairNLP/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 31ef92f8201f5cc468af82b8c5d6ce3ceedb083210ce0d7c4c6e8134dd73a3f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - bioc <3.0.0,>=2.0.0
    - python >=3.8
    - boto3 >=1.20.27
    - bpemb >=0.3.2
    - deprecated >=1.2.13
    - ftfy >=6.1.0
    - gdown >=4.4.0
    - gensim >=4.2.0
    - huggingface_hub >=0.10.0
    - janome >=0.4.2
    - langdetect >=1.0.9
    - lxml >=4.8.0
    - matplotlib-base >=2.2.3
    - more-itertools >=8.13.0
    - mpld3 >=0.3
    - pptree >=3.1
    - python-dateutil >=2.8.2
    - pytorch_revgrad >=0.2.0
    - regex >=2022.1.18
    - scikit-learn >=1.0.2
    - segtok >=1.5.11
    - sqlitedict >=2.0.0
    - tabulate >=0.8.10
    - pytorch >=1.5.0,!=1.8
    - tqdm >=4.63.0
    - transformer-smaller-training-vocab >=0.2.3
    - transformers >=4.25.0,<5.0.0
    - sentencepiece
    - urllib3 >=1.0.0
    - wikipedia-api >=0.5.7
    - semver <4.0.0,>=3.0.0
    - conllu >=4.0,<5.0.0

test:
  imports:
    - flair
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flairNLP/flair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A very simple framework for state-of-the-art NLP.
  doc_url: https://pypi.org/project/flair/
  dev_url: https://github.com/flairNLP/flair

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - BastianZim
