{% set name = "flair" %}
{% set version = "0.13.0" %}


package:
  name: python-flair
  version: {{ version }}

source:
  url: https://github.com/flairNLP/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bfe05beed2719f1eafec6840a0469fefcd4e8ec44c5dc4ee4869888e3fe245ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bpemb >=0.3.2
    - boto3
    - conllu >=4.0
    - deprecated >=1.2.4
    - ftfy
    - gdown ==4.4.0
    - gensim >=3.8.0
    - huggingface_hub >=0.10.0
    - hyperopt >=0.2.7
    - janome
    - langdetect
    - lxml
    - matplotlib-base >=2.2.3
    - more-itertools
    - mpld3 >=0.3
    - pptree
    - protobuf
    - python >=3.7
    - python-dateutil >=2.6.1
    - pytorch_revgrad
    - regex
    - scikit-learn >=0.21.3
    - segtok >=1.5.7
    - sentencepiece
    - sqlitedict >=1.6.0
    - tabulate
    - pytorch !=1.8,>=1.5.0
    - tqdm >=4.26.0
    - transformers >=4.0.0
    - transformer-smaller-training-vocab >=0.2.1
    - wikipedia-api
    - konoha <5.0.0,>=4.0.0

test:
  imports:
    - flair
    - flair.data
    - flair.models
  commands:
    - pytest
  requires:
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/flairNLP/flair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A very simple framework for state-of-the-art NLP.
  doc_url: https://pypi.org/project/flair/
  dev_url: https://github.com/flairNLP/flair

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - BastianZim
